// Clean-room mocap selection engine (Apache-2.0).
//
// Given the current pointer position and a target rectangle (in absolute device
// pixels), pick a recorded trajectory whose cumulative displacement lands the
// pointer inside the rect. The library is expanded at load time with small
// rotational perturbations, and a stretch+rotate fallback fits a path to the
// target when no base/perturbed sequence lands directly.
//
// This is an independent implementation of the publicly described technique.
// It does not use any third-party code or recorded data; the trajectories come
// from ./mocap-data.json, generated by ./generate-mocap.mjs.

import type { MocapLibrary, MocapMovement, MocapSequence } from "./types";

export interface Rect {
  left: number;
  top: number;
  right: number;
  bottom: number;
}

function rotateSequence(seq: MocapSequence, degrees: number, scale = 1): MocapSequence {
  const rad = (degrees * Math.PI) / 180;
  const cos = Math.cos(rad);
  const sin = Math.sin(rad);
  let total_dx = 0;
  let total_dy = 0;
  const movements: MocapMovement[] = seq.movements.map((m) => {
    const sx = m.dx * scale;
    const sy = m.dy * scale;
    const ndx = Math.round(sx * cos - sy * sin);
    const ndy = Math.round(sx * sin + sy * cos);
    total_dx += ndx;
    total_dy += ndy;
    return { dx: ndx, dy: ndy, dt: m.dt };
  });
  return {
    movements,
    total_dx,
    total_dy,
    click_down_dt: seq.click_down_dt,
    click_up_dt: seq.click_up_dt,
  };
}

export class MocapEngine {
  private sequences: MocapSequence[] = [];
  private rng: () => number;

  constructor(library: MocapLibrary, seed = 0x56455841) {
    // local PRNG so selection is reproducible in tests but varied at runtime
    let a = seed >>> 0;
    this.rng = () => {
      a |= 0;
      a = (a + 0x6d2b79f5) | 0;
      let t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
    this.load(library);
  }

  private load(library: MocapLibrary): void {
    const base = library.sequences;
    this.sequences = [...base];
    // Expand with a small set of rotational perturbations (-5..+5 deg) to
    // multiply landing points without exploding memory; the stretch/rotate
    // fallback covers any rect these still miss.
    const PERTURB_STEPS = 10;
    for (const seq of base) {
      for (let i = 1; i <= PERTURB_STEPS; i++) {
        const angle = -5 + (10 / (PERTURB_STEPS + 1)) * i;
        if (Math.abs(angle) < 1e-6) continue;
        this.sequences.push(rotateSequence(seq, angle));
      }
    }
  }

  get size(): number {
    return this.sequences.length;
  }

  private landsIn(seq: MocapSequence, x: number, y: number, rect: Rect): boolean {
    const fx = x + seq.total_dx;
    const fy = y + seq.total_dy;
    return fx >= rect.left && fx <= rect.right && fy >= rect.top && fy <= rect.bottom;
  }

  /** Pick a random sequence whose endpoint lands inside rect; null if none. */
  findSequenceLandingInRect(x: number, y: number, rect: Rect): MocapSequence | null {
    const matching = this.sequences.filter((s) => this.landsIn(s, x, y, rect));
    if (matching.length === 0) return null;
    return matching[Math.floor(this.rng() * matching.length)];
  }

  /**
   * Fallback: scale + rotate a base sequence so its endpoint lands on the rect
   * center. Used only when no recorded/perturbed sequence lands directly.
   */
  findSequenceWithStretchAndRotation(x: number, y: number, rect: Rect): MocapSequence | null {
    const cx = (rect.left + rect.right) / 2;
    const cy = (rect.top + rect.bottom) / 2;
    const wantDx = cx - x;
    const wantDy = cy - y;
    const wantDist = Math.hypot(wantDx, wantDy);
    const wantAngle = Math.atan2(wantDy, wantDx);

    let best: MocapSequence | null = null;
    let bestScaleDev = Infinity;
    // Prefer base sequences whose native length is closest to the target
    // distance (smallest scale deviation), to keep motion natural.
    for (const seq of this.sequences) {
      const seqDist = Math.hypot(seq.total_dx, seq.total_dy);
      if (seqDist < 1) continue;
      const seqAngle = Math.atan2(seq.total_dy, seq.total_dx);
      const scale = wantDist / seqDist;
      if (scale < 0.4 || scale > 2.6) continue; // avoid grotesque stretching
      const rotDeg = ((wantAngle - seqAngle) * 180) / Math.PI;
      if (Math.abs(rotDeg) > 35) continue; // keep rotations modest
      const scaleDev = Math.abs(Math.log(scale));
      if (scaleDev < bestScaleDev) {
        const candidate = rotateSequence(seq, rotDeg, scale);
        if (this.landsIn(candidate, x, y, rect)) {
          best = candidate;
          bestScaleDev = scaleDev;
        }
      }
    }
    return best;
  }
}
