#!/usr/bin/env node
/**
 * arch-report.mjs — generate docs/docs/governance/arch-compliance.mdx: each MODULARITY principle → the CI gate(s) that
 * enforce it → the current live evidence. The constitution promises "every principle names the practice
 * it comes from AND the gate that enforces it" (ARCHITECTURE.md §2/§4, P9 — an ungated rule is
 * aspirational). This makes that promise legible + checkable: a single artifact mapping P2·P3·P4·P6·P12
 * to their green gates, so "fully modular" is a claim backed by evidence, not prose.
 *
 *   node scripts/arch-report.mjs           # (re)generate docs/docs/governance/arch-compliance.mdx
 *   node scripts/arch-report.mjs --check    # verify every modularity gate is green (exit 1 if not); no write
 */
import { execSync } from "node:child_process";
import { writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");

/** Run one gate (via scripts/gates.mjs) and extract its single-line evidence (the ✓/✗ message). */
function gate(name) {
  try {
    const out = execSync(`node scripts/gates.mjs ${name}`, { cwd: ROOT, stdio: ["ignore", "pipe", "pipe"] }).toString();
    const ev = (out.split("\n").find((l) => l.includes("✓")) || "").replace(/.*✓\s*gate:[^\s—]+\s*—\s*/, "").trim();
    return { ok: true, ev };
  } catch (e) {
    const out = ((e.stdout || "") + (e.stderr || "")).toString();
    const ev = (out.split("\n").find((l) => l.includes("✗")) || out.trim().split("\n").pop() || "").replace(/.*✗\s*/, "").trim();
    return { ok: false, ev: ev.slice(0, 200) };
  }
}

const PRINCIPLES = [
  { p: "P2",  rule: "Couple only through contracts — no import reaches around a contract into a sibling module's internals (prod AND tests).", gates: ["isolation", "isolation-py", "test-isolation"] },
  { p: "P3",  rule: "Dependencies point inward to the kernel; the graph is acyclic (runtime depends on nothing above).", gates: ["graph", "graph-py"] },
  { p: "P4",  rule: "Cross a process/network boundary → a sealed, versioned, golden-pinned schema.", gates: ["schema", "contract-version"] },
  { p: "P6",  rule: "One public front door per module; internals are private.", gates: ["exports"] },
  { p: "P12", rule: "Every folder self-documents (README: concern · surface · deps).", gates: ["readme"] },
  { p: "P23", rule: "One writer per data carrier; a reader never re-derives a producer's data (data-flow ownership, architecture.calm.json).", gates: ["dataflow"] },
];

const rows = PRINCIPLES.map((pr) => {
  const results = pr.gates.map((g) => ({ g, ...gate(g) }));
  return { ...pr, results, ok: results.every((r) => r.ok) };
});
const allOk = rows.every((r) => r.ok);

if (!CHECK) {
  const md = [
    "---",
    'title: "Architecture compliance (generated)"',
    'description: "Generated map: every modularity principle and the gate that enforces it."',
    "---",
    "",
    "> Generated by `scripts/arch-report.mjs`. The constitution promises every principle names the practice",
    "> it comes from **and the gate that enforces it** ([Architecture](/governance/architecture) §2/§4, **P9**: an",
    "> ungated rule is aspirational). This is that map, live — each modularity principle → its CI gate(s) →",
    "> the current evidence. **P9 itself is the table**: every row is a green gate, not a README rule, so",
    '> "fully modular" is a claim backed by mechanical evidence. Regenerate with `node scripts/arch-report.mjs`;',
    "> `gate:arch-report` keeps it honest in CI.",
    "",
    "| Principle | Rule | Gate(s) | Evidence | Status |",
    "|---|---|---|---|---|",
    ...rows.map((r) => `| **${r.p}** | ${r.rule} | ${r.results.map((x) => `\`gate:${x.g}\``).join(" · ")} | ${r.results.map((x) => x.ev).join("; ")} | ${r.ok ? "✅" : "❌"} |`),
    "",
    `**Modularity verdict: ${allOk ? "all gates green — the v0.12 backend is fully modular by the constitution's own definition" : "RED — a modularity gate is failing"}.**`,
    "",
    "Per-service module structure (each a front-doored brick, independently testable): `meeting-api` =",
    "`{lifecycle · bot_spawn · collector · recordings · webhooks · scheduling · sessions · obs}`; `runtime` =",
    "the kernel (imports nothing above); `gateway`/`identity`/`agent-api` per their domains. The test lane is",
    "gated too (`gate:test-isolation`) — a test cannot reach across a module boundary where prod imports can't.",
    "",
  ].join("\n");
  writeFileSync(join(ROOT, "docs", "docs", "governance", "arch-compliance.mdx"), md);
  console.log(`arch-report → docs/docs/governance/arch-compliance.mdx (${allOk ? "all modularity gates green" : "SOME RED"})`);
} else if (allOk) {
  console.log(`  ✓ arch-report — ${rows.length} modularity principles each map to a green gate (P9)`);
} else {
  console.error("  ✗ arch-report — a modularity gate is RED:\n" +
    rows.filter((r) => !r.ok).map((r) => `    ${r.p}: ${r.results.filter((x) => !x.ok).map((x) => `${x.g} (${x.ev})`).join(", ")}`).join("\n"));
}

process.exit(allOk ? 0 : 1);
